// Prototype copy predates the supplied docs/copy.md. Formal key migration is tracked for M3.
export const copy = {
  brand: 'Schiild', home: 'ホーム', archive: 'アーカイブ', my: 'マイページ', settings: '設定', atelier: 'アトリエ',
  local: '端末内の試作版', localNote: '記録はこの端末に保存されます。ほかの人への共有・作品の生成・通知配信は接続前です。',
  today: '今日の記録', once: '1日1枚、今日を残す。', intro: '写真をひとつ。アトリエで重なり、ひとつのシールトへ。',
  create: 'アトリエをつくる', createFirst: '最初のアトリエをつくる', createHint: '写真を残す場所に、名前をつけてください。',
  atelierName: 'アトリエ名', namePlaceholder: '日々の断片', capacity: '定員', capacityHint: '2〜2000人。試作版では、この端末の記録だけを扱います。',
  invalidAtelier: '名前は1〜40文字、定員は2〜2000の整数で入力してください。',
  capture: '今日のシールを撮る', recorded: '今日のシールは記録されています', recordedHint: '同じシールを、別のアトリエにも記録できます。',
  yourAteliers: 'あなたのアトリエ', open: '開く', back: '戻る', cancel: 'キャンセル', close: '閉じる',
  canvas: '今日のキャンバス', canvasNote: '構図は生成エンジン接続後に表示されます。',
  anonymous: 'メンバーは匿名の矩形で表示されます。', members: '{n} の区画', capacityLabel: '定員 {n}',
  localRecord: 'この端末の記録', add: '今日のシールをここにも記録', added: 'このアトリエに記録済み',
  works: 'シールト', noWorks: '毎日の作品は、ここに残ります。', noWorksHint: '生成エンジンの接続後、作品を開封できます。',
  photos: 'シール', noPhotos: '今日のシールを撮って、最初の記録を残してください。',
  cameraTitle: '今日のシール', cameraHint: '正方形の中に、今日をひとつ。', permissionTitle: 'カメラへのアクセスが必要です',
  permissionBody: 'シールはアプリ内のカメラで撮影します。端末の設定でカメラを許可してください。', allow: 'カメラを許可', openSettings: '端末の設定を開く',
  cameraError: 'カメラを使用できません。端末の設定を確認して、もう一度開いてください。',
  shutter: '撮影する', review: '今日のシールを確認', confirmTitle: '今日のシールは一度きりです',
  confirmBody: '確定したシールは取り消し・差し替えできません。この端末に記録します。', confirm: 'このシールを記録', chooseAtelier: '記録するアトリエ',
  chooseRequired: 'アトリエを1つ以上選択してください。', retake: '撮り直す', saving: '保存中',
  saveError: '保存を完了できませんでした。撮影画像は端末に保持されています。同じ画面から再度保存してください。',
  dateChanged: '記録する日付が切り替わりました。ホームに戻って今日のシールを撮影してください。',
  stored: '端末に記録しました', notSent: 'サーバーには送信していません。', count: '{n} 枚のシール', atelierCount: '{n} のアトリエ',
  timezone: '時刻の表示', tokyo: '日本時間（JST）', utc: '協定世界時（UTC）', timeNote: '記録日はUTC 00:00に切り替わります。日本時間では09:00です。',
  about: 'この試作版について', aboutBody: 'カメラ撮影・端末への記録・アトリエ別の整理を確認できます。認証、複数端末の同期、参加コード、作品の生成、抽選、配信は未接続です。',
  delete: '端末内のデータを削除', deleteTitle: 'この端末の記録を削除します',
  disappears: '消えるもの', disappearsBody: 'この端末のシール、アトリエ、設定。',
  remains: '作品に残るもの', remainsBody: 'この試作版では、共有作品は作成されていません。サーバー上のアカウントもありません。',
  deleteConfirm: '端末内のデータを削除する', storageError: '記録を読み込めませんでした。保存データは上書きしていません。アプリを再起動してください。',
  genericError: '操作を完了できませんでした。記録は変更されていません。', loading: '記録を読み込んでいます',
  detail: 'シールの記録', dimensions: '1080 × 1080 / JPEG', recordedAt: '記録日', noAtelier: 'アトリエをつくって、今日の記録を始めてください。',
} as const;
export function t(key: keyof typeof copy, values: Record<string, string | number> = {}) { return Object.entries(values).reduce<string>((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), copy[key]); }
