import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const origin=process.env.DEMO_URL||'http://localhost:8085';
const browser=await chromium.launch({headless:true,...(process.env.DEMO_BROWSER?{executablePath:process.env.DEMO_BROWSER}:{}),args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const errors=[];
async function camera(page){await page.goto(origin);page.on('pageerror',error=>errors.push(error.message));await page.getByTestId('today-board').waitFor();await page.getByRole('button',{name:'このアトリエに1日1枚',exact:true}).click();await page.getByRole('button',{name:'次へ',exact:true}).click();}
async function fresh(options={}){const context=await browser.newContext({viewport:{width:390,height:844},permissions:['camera'],...options});return {context,page:await context.newPage()};}
try{
 await mkdir('test-results',{recursive:true});
 const recovery=await fresh();
 await recovery.page.addInitScript(()=>{const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);let denied=true;navigator.mediaDevices.getUserMedia=async constraints=>{if(denied){denied=false;throw new DOMException('denied','NotAllowedError');}return original(constraints);};});
 await camera(recovery.page);await recovery.page.getByText('カメラが使えません',{exact:true}).waitFor();assert.equal(await recovery.page.locator('.shutter').isDisabled(),true);
 await recovery.page.getByRole('button',{name:'許可の手順を見る',exact:true}).click();await recovery.page.locator('#camera-help').waitFor();assert.equal(await recovery.page.locator('#camera-help').evaluate(element=>element===document.activeElement),true);
 const select=recovery.page.locator('#camera-help select');for(const value of ['ios','android','desktop','other']){await select.selectOption(value);assert.equal(await recovery.page.locator('#camera-help ol li').count(),3);}
 await select.selectOption('ios');await recovery.page.screenshot({path:'test-results/camera-help.png',fullPage:true});assert.equal(await recovery.page.locator('#camera-help input').inputValue(),origin.replace(/\/$/,'')+'/');
 await recovery.page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw new DOMException('clipboard','NotAllowedError');}}});});await recovery.page.getByRole('button',{name:'URLをコピーする',exact:true}).click();await recovery.page.getByRole('status').filter({hasText:'表示されたURLを選択し、コピーしてください。'}).waitFor();assert.equal(await recovery.page.locator('#camera-help input').evaluate(input=>input.selectionEnd===input.value.length&&input.selectionStart===0),true);
 await recovery.page.getByRole('button',{name:'カメラを再確認する',exact:true}).last().click();await recovery.page.locator('.shutter:not([disabled])').waitFor();assert.equal(await recovery.page.locator('#camera-help').count(),0);await recovery.page.locator('.shutter').click();await recovery.page.getByRole('dialog').waitFor();
 assert.deepEqual(await recovery.page.locator('.confirm-photo').evaluate(async image=>{await image.decode();return [image.naturalWidth,image.naturalHeight];}),[1080,1080]);assert.equal(await recovery.page.locator('input[type=file]').count(),0);await recovery.context.close();
 for(const [name,body] of [['NotFoundError','カメラが見つかりません。'],['NotReadableError','カメラを起動できません。'],['camera_unsupported','この画面ではカメラを利用できません。'],['camera_insecure','カメラは安全な接続でのみ使えます。']]){
  const item=await fresh();await item.page.addInitScript(name=>{if(name==='camera_insecure')Object.defineProperty(window,'isSecureContext',{value:false});else if(name==='camera_unsupported')Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:undefined});else navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('test',name);};},name);
  await camera(item.page);await item.page.getByRole('alert').filter({hasText:body}).waitFor();await item.page.getByRole('button',{name:'許可の手順を見る',exact:true}).click();await item.page.locator('#camera-help').waitFor();await item.context.close();
 }
 // Camera constraints may fail on hardware; fallback still uses a live camera.
 const fallback=await fresh();await fallback.page.addInitScript(()=>{const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);let first=true;navigator.mediaDevices.getUserMedia=async constraints=>{if(first){first=false;throw new DOMException('constraints','OverconstrainedError');}return original(constraints);};});await camera(fallback.page);await fallback.page.locator('.shutter:not([disabled])').waitFor();await fallback.context.close();
 // A failed video preview releases hardware before the user retries.
 const playback=await fresh();await playback.page.addInitScript(()=>{window.testStreams=[];const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async constraints=>{const stream=await original(constraints);window.testStreams.push(stream);return stream;};const play=HTMLMediaElement.prototype.play;let first=true;HTMLMediaElement.prototype.play=function(){if(first){first=false;return Promise.reject(new DOMException('preview','NotSupportedError'));}return play.call(this);};});await camera(playback.page);await playback.page.getByRole('alert').waitFor();assert.equal(await playback.page.evaluate(()=>window.testStreams[0].getTracks().every(track=>track.readyState==='ended')),true);await playback.page.getByRole('button',{name:'カメラを再確認する',exact:true}).click();await playback.page.locator('.shutter:not([disabled])').waitFor();
 await playback.page.evaluate(()=>{const track=window.testStreams.at(-1).getVideoTracks()[0];track.dispatchEvent(new Event('ended'));});await playback.page.getByRole('alert').filter({hasText:'カメラとの接続が切れました。'}).waitFor();await playback.context.close();
 // Leaving while a permission request is pending must not keep a camera running.
 const pending=await fresh();await pending.page.addInitScript(()=>{const original=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async constraints=>{const stream=await original(constraints);window.testPending=stream;await new Promise(resolve=>window.testRelease=resolve);return stream;};});await camera(pending.page);await pending.page.waitForFunction(()=>window.testPending);await pending.page.locator('.subheader').getByRole('button',{name:'戻る',exact:true}).click();await pending.page.getByTestId('today-board').waitFor();await pending.page.evaluate(()=>window.testRelease());await pending.page.waitForFunction(()=>window.testPending.getTracks().every(track=>track.readyState==='ended'));await pending.context.close();
 assert.deepEqual(errors,[]);console.log('Camera permission guidance, allowed retry and 1080 capture, missing/busy/unsupported/insecure errors, constraints fallback, stopped preview and late-request cleanup: passed');
}finally{await browser.close();}
