import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {realpathSync} from 'node:fs';
import {mkdtemp,mkdir,cp,writeFile,rm} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import path from 'node:path';
import os from 'node:os';
import {pathToFileURL} from 'node:url';
import sharp from 'sharp';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
const bundle=process.env.DEMO_WORKER_BUNDLE,php=process.env.DEMO_PHP;
test('workerd and durable SQLite run complete shared generation against the actual PHP gateway',{skip:!bundle||!php},async()=>{
 const require=createRequire(import.meta.url),wranglerRequire=createRequire(realpathSync(require.resolve('wrangler/package.json')));
 const {Miniflare,convertV4MiniflareOptions}=await import(pathToFileURL(wranglerRequire.resolve('miniflare')).href);
 const root=await mkdtemp(path.join(os.tmpdir(),'schiild-runtime-')),site=path.join(root,'site'),directory=path.join(root,'images'),secret='f'.repeat(64);
 const googleClient='123456789-runtime.apps.googleusercontent.com',{privateKey,publicKey}=await generateKeyPair('RS256'),googleJwk=await exportJWK(publicKey);googleJwk.kid='runtime';
 await mkdir(site);await mkdir(directory);await cp(new URL('../xserver/storage.php',import.meta.url),path.join(site,'storage.php'));
 await writeFile(path.join(site,'.storage-config.php'),`<?php return ['secret'=>'${secret}','directory'=>'${directory.replaceAll('\\','/')}'];`);
 const child=spawn(php,['-S','127.0.0.1:8793','-t',site],{windowsHide:true,stdio:'ignore'});let mf;
 try{
  for(let n=0;n<50;n++){try{await fetch('http://127.0.0.1:8793/storage.php');break;}catch{await new Promise(r=>setTimeout(r,100));}}
  mf=new Miniflare(convertV4MiniflareOptions({name:'test',scriptPath:bundle,modules:true,compatibilityDate:'2026-10-08',compatibilityFlags:['nodejs_compat'],durableObjects:{ATELIERS:{className:'AtelierDirectory',useSQLite:true}},bindings:{ALLOWED_ORIGINS:'http://localhost:8085',XSERVER_STORAGE_URL:'https://schiild.pickleballnavi.jp/storage.php',XSERVER_STORAGE_SECRET:secret,GOOGLE_CLIENT_ID:googleClient},outboundService:async request=>{
   const url=new URL(request.url);
   if(url.href==='https://www.googleapis.com/oauth2/v3/certs')return Response.json({keys:[googleJwk]},{headers:{'Cache-Control':'public, max-age=3600'}});
   assert.equal(url.hostname,'schiild.pickleballnavi.jp');url.protocol='http:';url.hostname='127.0.0.1';url.port='8793';
   const response=await fetch(url,{method:request.method,headers:Object.fromEntries(request.headers),...(request.method==='PUT'?{body:await request.arrayBuffer()}:{})});
   return response;
  }}));
  const call=async(action,values={},credential='a'.repeat(64))=>{const response=await mf.dispatchFetch('https://api.example/api/atelier',{method:'POST',headers:{Origin:'http://localhost:8085',Authorization:`Bearer ${credential}`},body:JSON.stringify({action,...values})});const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));return body;};
  const first='a'.repeat(64),second='b'.repeat(64),room=await call('create',{name:'ふたりの窓',capacity:2});await call('join',{code:room.code},second);
  const photo=await sharp({create:{width:1080,height:1080,channels:3,background:'#c39582'}}).jpeg().toBuffer();
  await Promise.all([first,second].map(credential=>call('post',{code:room.code,day:room.day,photo:`data:image/jpeg;base64,${photo.toString('base64')}`},credential)));
  const state=await call('state',{code:room.code});assert.equal(state.postedSlots.length,2);
  const draft=await call('draft',{code:room.code,day:room.day},second);assert.equal(draft.provisional,true);assert.equal(draft.count,2);
  assert.deepEqual(await call('state',{code:room.code}),state);
  assert.equal((await sharp(Buffer.from(draft.image.split(',')[1],'base64')).metadata()).width,128);
  await call('generate',{code:room.code,day:room.day});
  const made=await call('work',{code:room.code,day:room.day}),guest=await call('work',{code:room.code,day:room.day},second);
  assert.equal(made.image,guest.image);const meta=await sharp(Buffer.from(made.image.split(',')[1],'base64')).metadata();assert.equal(meta.width,128);
  assert.equal(made.image,draft.image);
  const global=await call('global',{day:room.day}),globalGuest=await call('global',{day:room.day},second),globalOutside=await call('global',{day:room.day},'c'.repeat(64));
  assert.equal(global.image,globalGuest.image);assert.equal(global.image,globalOutside.image);assert.equal(global.count,2);assert.equal(globalOutside.x,undefined);
  assert.equal(global.positions.length,2);assert(global.positions.includes(global.y*256+global.x));assert.deepEqual(global.positions,globalOutside.positions);
  assert.equal((await sharp(Buffer.from(global.image.split(',')[1],'base64')).metadata()).width,256);
  const account=await call('account.register',{username:'runtime_member',password:'runtime-password-29',name:'あさ'},first);
  assert.equal(account.account.ateliers[0].code,room.code);assert.equal(account.account.ateliers[0].canGenerate,true);
  const login=await call('account.login',{username:'runtime_member',password:'runtime-password-29'},'c'.repeat(64));
  const start=await call('account.google.start',{},login.token);
  const idToken=await new SignJWT({nonce:start.nonce,email:'runtime@gmail.com',email_verified:true}).setProtectedHeader({alg:'RS256',kid:'runtime'}).setSubject('runtime-google-person').setIssuer('https://accounts.google.com').setAudience(googleClient).setIssuedAt().setExpirationTime('5m').sign(privateKey);
  const linked=await call('account.google',{idToken},login.token);assert.equal(linked.account.username,'runtime_member');assert.equal(linked.account.ateliers[0].code,room.code);
  const replay=await mf.dispatchFetch('https://api.example/api/atelier',{method:'POST',headers:{Authorization:`Bearer ${login.token}`},body:JSON.stringify({action:'account.google',idToken})});assert.equal(replay.status,401);
  const outside='4'.repeat(64),again=await call('account.google.start',{},outside);
  const returningToken=await new SignJWT({nonce:again.nonce,email:'runtime@gmail.com',email_verified:true}).setProtectedHeader({alg:'RS256',kid:'runtime'}).setSubject('runtime-google-person').setIssuer('https://accounts.google.com').setAudience(googleClient).setIssuedAt().setExpirationTime('5m').sign(privateKey);
  const returning=await call('account.google',{idToken:returningToken},outside);assert.equal(returning.account.username,'runtime_member');assert.equal((await call('state',{code:room.code},returning.token)).canGenerate,true);
  assert.equal((await call('state',{code:room.code},login.token)).canGenerate,true);assert.equal((await call('global',{day:room.day},login.token)).x,global.x);
  await call('leave',{code:room.code},login.token);
  assert.equal((await call('account.me',{},login.token)).account.ateliers.length,0);
  const remaining=await call('state',{code:room.code},second);assert.equal(remaining.members,1);assert.equal(remaining.canGenerate,true);assert.equal(remaining.postedSlots.length,2);
  assert.equal((await call('work',{code:room.code,day:room.day},second)).image,made.image);assert.equal((await call('global',{day:room.day},login.token)).image,global.image);
  assert.equal((await call('join',{code:room.code},login.token)).hasPhoto,true);
  const different=await call('create',{name:'別の写真の窓',capacity:5},login.token),reused=await call('create',{name:'選んだ追加先',capacity:2},login.token);
  const blue=await sharp({create:{width:1080,height:1080,channels:3,background:'#87a6b0'}}).jpeg().toBuffer();
  await call('post',{code:different.code,day:room.day,photo:'data:image/jpeg;base64,'+blue.toString('base64')},login.token);
  assert.notEqual((await call('post.photo',{sourceCode:different.code,day:room.day},login.token)).photo,(await call('post.photo',{sourceCode:room.code,day:room.day},login.token)).photo);
  const copied=await call('reuse',{sourceCode:room.code,day:room.day,codes:[reused.code,different.code]},login.token);
  assert.deepEqual(copied.results.map(value=>[value.done,value.error]),[[true,undefined],[false,'already_recorded']]);
  const reusedDraft=await call('draft',{code:reused.code,day:room.day},login.token);assert(reusedDraft.area.pixels>0);
  assert.equal((await call('global',{day:room.day},login.token)).area.pixels,1);
  const area=await call('area',{},login.token);assert.equal(area.global.pixels,1);assert.equal(area.atelier.days,3);assert.equal(area.atelier.pixels,made.area.pixels+reusedDraft.area.pixels+(await call('state',{code:different.code},login.token)).area.pixels);
  await call('leave',{code:room.code},login.token);assert.equal((await call('area',{},login.token)).atelier.pixels,area.atelier.pixels);
  await call('account.logout',{},login.token);
  const expired=await mf.dispatchFetch('https://api.example/api/atelier',{method:'POST',headers:{Authorization:`Bearer ${login.token}`},body:JSON.stringify({action:'account.me'})});assert.equal(expired.status,401);
  const invalid=await mf.dispatchFetch('https://api.example/api/atelier',{method:'POST',headers:{Authorization:`Bearer ${first}`},body:'[]'});assert.equal(invalid.status,400);
  await call('account.delete',{confirmUsername:'runtime_member',password:'runtime-password-29'},returning.token);
  for(const credential of [first,login.token,returning.token]){const rejected=await mf.dispatchFetch('https://api.example/api/atelier',{method:'POST',headers:{Authorization:`Bearer ${credential}`},body:JSON.stringify({action:'account.me'})});assert.equal(rejected.status,401);assert.equal((await rejected.json()).error,'account_deleted');}
  assert.equal((await call('work',{code:room.code,day:room.day},second)).image,made.image);assert.equal((await call('global',{day:room.day},second)).image,global.image);
  const fresh=await call('account.register',{username:'runtime_member',password:'fresh-account-password-29'},'5'.repeat(64));assert.equal(fresh.account.ateliers.length,0);assert.equal((await call('area',{},fresh.token)).global.pixels,0);
 }finally{if(mf)await mf.dispose();child.kill();await new Promise(resolve=>child.once('exit',resolve));await rm(root,{recursive:true,force:true});}
});
