import React,{useState} from 'react';
import {t} from './copy';
import type {Account} from './shared-api';
import type {Preferences} from './preferences';
import GoogleSignIn from './GoogleSignIn';
export default function AccountPage({account,joined,name,onAuthenticate,onGoogle,onName,onArchive,onSettings,onCustody}:{account:Account|null;joined:number;name:string;onAuthenticate:(register:boolean,username:string,password:string,name:string)=>Promise<void>;onGoogle:(idToken:string)=>Promise<void>;onName:(name:string)=>Promise<void>;onArchive:()=>void;onSettings:()=>void;onCustody:(code:string,day:string)=>void}){
 const [register,setRegister]=useState(false),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[displayName,setDisplayName]=useState(account?.name??name),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(task:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await task();setPassword('');}catch(cause){setError(cause instanceof Error?cause.message:t('error.server.body'));}finally{setBusy(false);}}
 return <section className="account-page"><h1>{t('me.title')}</h1>{account?<><p className="mono">@{account.username} ／ {t('me.since',{date:account.since})}</p><div className="stats"><div><span>{t('me.stat.joined')}</span><b>{account.ateliers.length}</b></div><div><span>{t('me.stat.custody')}</span><b>{account.custody.length}</b></div></div><form onSubmit={event=>{event.preventDefault();void submit(()=>onName(displayName));}}><label className="field">{t('demo.account.name')}<input value={displayName} maxLength={40} required onChange={event=>setDisplayName(event.target.value)}/></label><button className="button" disabled={busy}>{t('common.done')}</button></form><h2>{t('me.section.custody')}</h2>{account.custody.length?account.custody.map(item=><button className="atelier-select" key={item.code+item.day} onClick={()=>onCustody(item.code,item.day)}><span>{item.name}</span><span className="mono">{item.day}</span></button>):<p>{t('empty.custody.title')}</p>}</>:<><p>{t('demo.account.guest')}</p><p className="mono">{t('me.stat.joined')} {joined}</p><h2>{t('settings.account')}</h2><div className="choice"><button aria-pressed={!register} onClick={()=>{setRegister(false);setError('');}}>{t('demo.account.login')}</button><button aria-pressed={register} onClick={()=>{setRegister(true);setError('');}}>{t('demo.account.register')}</button></div><form onSubmit={event=>{event.preventDefault();void submit(()=>onAuthenticate(register,username,password,displayName));}}><label className="field">{t('demo.account.id')}<input value={username} autoComplete="username" autoCapitalize="none" spellCheck={false} minLength={3} maxLength={24} required onChange={event=>setUsername(event.target.value)}/></label>{register&&<label className="field">{t('demo.account.name')}<input value={displayName} maxLength={40} onChange={event=>setDisplayName(event.target.value)}/></label>}<label className="field">{t('demo.account.password')}<input type="password" value={password} autoComplete={register?'new-password':'current-password'} minLength={register?12:1} maxLength={128} required onChange={event=>setPassword(event.target.value)}/></label><p className="shared-note">{t('demo.account.rules')}</p><button className="button" disabled={busy}>{t(busy?'common.loading':register?'demo.account.register':'demo.account.login')}</button></form><p className="shared-note">{t('demo.account.scope')}</p><p className="shared-note">{t('demo.account.recovery')}</p></>}<GoogleSignIn linkedEmail={account?.googleEmail} disabled={busy} onAuthenticate={async idToken=>{if(busy)return;setBusy(true);setError('');try{await onGoogle(idToken);}finally{setBusy(false);}}}/>{error&&<p className="error" role="alert">{error}</p>}<button className="atelier-select" onClick={onArchive}>{t('me.link.archive')}</button><button className="atelier-select" onClick={onSettings}>{t('me.link.settings')}</button></section>;
}
export function SettingsPage({value,onChange,account,onAccount,onLogout}:{value:Preferences;onChange:(value:Preferences)=>void;account:Account|null;onAccount:()=>void;onLogout:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="settings-page"><h1>{t('settings.title')}</h1><button className="atelier-select" onClick={onAccount}>{t('settings.account')}</button><label className="setting-toggle"><span>{t('demo.settings.motion')}</span><input type="checkbox" checked={value.reduceMotion} onChange={event=>onChange({...value,reduceMotion:event.target.checked})}/></label><h2>{t('settings.notifications')}</h2><p>{t('demo.settings.notifications')}</p><p className="shared-note">{t('demo.settings.notification_privacy')}</p><h2>{t('settings.privacy')}</h2><p>{t('demo.settings.privacy')}</p>{account&&<button className="button secondary" disabled={busy} onClick={()=>{setBusy(true);setError('');void onLogout().catch(cause=>setError(cause instanceof Error?cause.message:t('error.server.body'))).finally(()=>setBusy(false));}}>{t('settings.logout')}</button>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
