// Approved demo-only additions. Production copy and requirements remain unchanged.
export const demoCopy={
 'demo.atelier.delete':'アトリエを削除する',
 'demo.atelier.delete_body':'この端末内の「{name}」と履歴を削除します。元に戻せません。',
 'demo.shared.create_note':'友達を招待して、今日の1枚を同じシールトに残せます。',
 'demo.shared.join_now':'参加すると、今日から1枚を記録できます。',
 'demo.shared.share_note':'このリンクか8文字のコードを友達に渡してください。',
 'demo.shared.photo_notice':'確定すると写真をこのアトリエに送信します。参加者の写真から1枚のシールトをつくります。',
 'demo.shared.generate':'シールトを生成する',
 'demo.shared.generating':'シールトを生成しています',
 'demo.shared.generate_note':'みんなの写真が集まったら生成できます。生成後は今日の写真を追加できません。',
 'demo.shared.generate_confirm':'今日のシールトを生成します',
 'demo.shared.generate_body':'現在の{n}枚から生成します。まだ記録していない人は、生成後に今日の写真を追加できません。',
 'demo.shared.before_photo':'今日の1枚を記録すると、友達の写真と一緒にシールトに残せます。',
 'demo.shared.wait':'記録した写真は保存されています。作成者が生成すると、同じシールトを開けます。',
 'demo.shared.members':'参加 {n}人 ／ 定員 {cap}人',
 'demo.shared.custody.other':'このアトリエの参加者が預かります',
 'demo.shared.unavailable':'つながりませんでした。時間をおいて、もう一度試してください。',
 'demo.shared.image_invalid':'1080×1080の写真を送れませんでした。撮影した写真を確認してください。',
 'demo.shared.no_photos':'今日の1枚を記録してから生成してください。',
 'demo.shared.forbidden':'このアトリエへの参加を確認してください。生成できるのは作成者です。',
 'demo.shared.back':'アトリエに戻る',
 'demo.shared.refresh':'もう一度読み込む',
 'demo.shared.saved':'今日の1枚を記録しました。',
 'demo.shared.local':'ひとりで試す',
};
