// Approved demo-only additions. Production copy and requirements remain unchanged.
export const demoCopy={
 'demo.camera.help':'許可の手順を見る',
 'demo.camera.retry':'カメラを再確認する',
 'demo.camera.manual':'カメラの許可は、お使いのブラウザや端末の設定で変更します。下の手順で確認してください。',
 'demo.camera.browser':'使っているブラウザ',
 'demo.camera.guide.ios':'iPhone・iPad / Safari',
 'demo.camera.guide.android':'Android / Chrome',
 'demo.camera.guide.desktop':'PC / Chrome・Edge',
 'demo.camera.guide.other':'その他のブラウザ',
 'demo.camera.ios.site':'Safariで{site}を開き、アドレスバーのページメニューから「ウェブサイトの設定」を開きます。「カメラ」を「許可」に変更します。',
 'demo.camera.ios.system':'見つからない場合は、端末の「設定」→「アプリ」→「Safari」→「カメラ」を確認します。ほかのブラウザでは、そのアプリのカメラ許可も確認してください。',
 'demo.camera.android.site':'Chromeの「︙」→「設定」→「サイトの設定」→「カメラ」を開きます。カメラの使用を許可し、ブロック中の{site}を「許可」に変更します。',
 'demo.camera.android.system':'端末の「設定」→「アプリ」→「Chrome」→「権限」→「カメラ」も許可します。端末全体のカメラへのアクセスがオフなら、オンにします。',
 'demo.camera.desktop.site':'アドレスバー左側のサイト情報から、{site}のカメラを許可します。項目がなければブラウザの「設定」で「カメラ」を検索し、このサイトのブロックを解除します。',
 'demo.camera.desktop.system':'Windowsでは「設定」→「プライバシーとセキュリティ」→「カメラ」でカメラへのアクセスとデスクトップアプリのアクセスを許可します。Macでは「システム設定」→「プライバシーとセキュリティ」→「カメラ」を確認します。',
 'demo.camera.other.site':'ブラウザのサイト設定で{site}のカメラ許可を確認します。SafariのMac版では「設定」→「Webサイト」→「カメラ」、Firefoxでは「設定」→「プライバシーとセキュリティ」→「カメラ」を確認します。',
 'demo.camera.other.system':'端末の設定で、使っているブラウザにカメラの使用を許可してください。設定項目の名前は端末やバージョンによって異なります。',
 'demo.camera.return':'この撮影画面へ戻り、「カメラを再確認する」を押します。許可の確認が出たら「許可」を選んでください。反映されない場合はページを再読み込みし、撮影を開き直します。',
 'demo.camera.embedded':'アプリ内のブラウザやプレビューで開いている場合は、下のURLをコピーしてSafari・Chrome・Edgeで開いてください。',
 'demo.camera.url':'ブラウザで開くURL',
 'demo.camera.copy':'URLをコピーする',
 'demo.camera.copy_manual':'表示されたURLを選択し、コピーしてください。',
 'demo.camera.missing':'カメラが見つかりません。PCではカメラを接続し、端末がカメラを認識しているか確認してください。',
 'demo.camera.busy':'カメラを起動できません。他のアプリやタブでカメラを使っている場合は閉じて、もう一度試してください。端末のカメラ許可も確認してください。',
 'demo.camera.unsupported':'この画面ではカメラを利用できません。URLをコピーしてSafari・Chrome・Edgeで開いてください。',
 'demo.camera.insecure':'カメラは安全な接続でのみ使えます。https://schiild.pickleballnavi.jp/ をブラウザで開いてください。',
 'demo.camera.interrupted':'カメラとの接続が切れました。撮影を続けるには、カメラを再確認してください。',
 'demo.camera.unknown':'カメラを起動できませんでした。許可の設定を確認して、もう一度試してください。',
 'demo.atelier.delete':'アトリエを削除する',
 'demo.atelier.delete_body':'この端末内の「{name}」と履歴を削除します。元に戻せません。',
 'demo.atelier.leave':'アトリエを抜ける',
 'demo.atelier.leave_note':'アトリエを抜けても、記録した写真・作品・GLOBALは残ります。招待コードで再び参加できます。',
 'demo.atelier.leave_creator':'作成者が抜けると、生成権限は残っている参加者へ引き継がれます。',
 'demo.atelier.leave_slots':'投稿済みの区画を別の参加者が使えるのは、翌日からです。',
 'demo.atelier.slots_reserved':'今日の投稿済み区画が残っているため、翌日から参加できます。',
 'demo.shared.create_note':'友達を招待して、今日の1枚を同じシールトに残せます。',
 'demo.shared.join_now':'参加すると、今日から1枚を記録できます。',
 'demo.shared.share_note':'このリンクか8文字のコードを友達に渡してください。',
 'demo.shared.photo_notice':'確定すると写真をこのアトリエに送信します。参加者の写真から1枚のシールトをつくります。',
 'demo.shared.generate':'シールトを生成する',
 'demo.shared.generating':'シールトを生成しています',
 'demo.shared.generate_note':'みんなの写真が集まったら生成できます。生成後は今日の写真を追加できません。',
 'demo.shared.generate_confirm':'今日のシールトを生成します',
 'demo.shared.generate_body':'現在の{n}枚から生成します。まだ記録していない人は、生成後に今日の写真を追加できません。',
 'demo.shared.before_photo':'今日の1枚を記録すると、友達の写真と一緒にシールトに残せます。',
 'demo.shared.wait':'記録した写真は保存されています。作成者が生成すると、同じシールトを開けます。',
 'demo.shared.members':'参加 {n}人 ／ 定員 {cap}人',
 'demo.shared.custody.other':'このアトリエの参加者が預かります',
 'demo.shared.unavailable':'つながりませんでした。時間をおいて、もう一度試してください。',
 'demo.shared.image_invalid':'1080×1080の写真を送れませんでした。撮影した写真を確認してください。',
 'demo.shared.no_photos':'今日の1枚を記録してから生成してください。',
 'demo.shared.forbidden':'このアトリエへの参加を確認してください。生成できるのは作成者です。',
 'demo.shared.back':'アトリエに戻る',
 'demo.shared.refresh':'もう一度読み込む',
 'demo.shared.saved':'今日の1枚を記録しました。',
 'demo.shared.local':'ひとりで試す',
 'demo.global.sample':'サンプル作品',
 'demo.global.live':'今日の投稿に合わせて更新されます。翌日から作品は固定されます。',
 'demo.global.empty':'この日のGLOBAL SCHIILDはまだありません。',
 'demo.global.no_pixel':'この日の作品に、あなたのシールは含まれていません。',
 'demo.account.guest':'このブラウザで試しています',
 'demo.account.id':'アカウントID',
 'demo.account.name':'表示名',
 'demo.account.password':'パスワード',
 'demo.account.login':'ログインする',
 'demo.account.register':'アカウントをつくる',
 'demo.account.rules':'IDは英小文字・数字・_・-で3〜24文字。パスワードは12〜128文字です。',
 'demo.account.scope':'ログインすると、別の端末でも参加アトリエと預かり作品を確認できます。ひとりで試す履歴は、このブラウザにだけ残ります。',
 'demo.account.recovery':'メール確認とパスワードの再発行は、このデモではできません。',
 'demo.account.invalid':'ID、表示名、パスワードの入力内容を確認してください。',
 'demo.account.taken':'このIDでは登録できません。別のIDを入力してください。',
 'demo.account.linked':'このブラウザの参加情報は、すでにアカウントに連携しています。ログインしてください。',
 'demo.account.login_invalid':'IDまたはパスワードを確認してください。',
 'demo.account.limited':'試行回数の制限に達しました。時間をおいて、もう一度試してください。',
 'demo.account.expired':'ログインの有効期限が切れました。もう一度ログインしてください。',
 'demo.settings.motion':'開封・ズームの演出を省略する',
 'demo.settings.notifications':'このデモでは通知を配信しません。',
 'demo.settings.notification_privacy':'他の人が記録したかどうかは、通知に含まれません。',
 'demo.settings.privacy':'共有写真と作品はXserver、参加情報とアカウントはCloudflareに保存します。パスワードはハッシュで保存します。サンプル履歴と演出の設定は、このブラウザに保存します。',
};
