// DEMO ONLY. Inspect the shared GLOBAL image; no access to other people's source photos.
import React,{useEffect,useRef,useState} from 'react';
import {t} from './copy';
import {boundView,zoomAt,pixelAt,pixelPosition,fullView,MAX_SCALE} from './global-view';
import type {View,Point} from './global-view';
type Pointer={x:number;y:number};
type Gesture={view:View;points:Pointer[]};
const middle=(a:Pointer,b:Pointer):Point=>({x:(a.x+b.x)/2,y:(a.y+b.y)/2});
const distance=(a:Pointer,b:Pointer)=>Math.hypot(a.x-b.x,a.y-b.y);
export default function GlobalExplorer({image,positions,mine,sample=false}:{image:string;positions?:number[];mine?:Point;sample?:boolean}){
 const stage=useRef<HTMLDivElement>(null),bitmap=useRef<HTMLImageElement>(null),canvas=useRef<HTMLCanvasElement|null>(null),pointers=useRef(new Map<number,Pointer>()),gesture=useRef<Gesture|null>(null);
 const [size,setSize]=useState(0),[view,setView]=useState<View>(fullView),[selected,setSelected]=useState<Point|null>(null),[color,setColor]=useState('');
 const sizeRef=useRef(0),viewRef=useRef(view),tap=useRef<{pointerId:number;point:Point;time:number;moved:boolean}|null>(null),lastTap=useRef<{point:Point;time:number}|null>(null);
 function apply(next:View){const bounded=boundView(next,sizeRef.current);viewRef.current=bounded;setView(bounded);}
 function centered(clientX:number,clientY:number):Point{const box=stage.current!.getBoundingClientRect();return {x:clientX-box.left-box.width/2,y:clientY-box.top-box.height/2};}
 function seed(){gesture.current={view:{...viewRef.current},points:[...pointers.current.values()].map(point=>({...point}))};}
 function read(pixel:Point){const ctx=canvas.current?.getContext('2d');if(!ctx)return;try{const rgb=ctx.getImageData(pixel.x,pixel.y,1,1).data;setColor('#'+[...rgb.slice(0,3)].map(value=>value.toString(16).padStart(2,'0')).join('').toUpperCase());}catch{setColor('');}}
 function choose(pixel:Point){setSelected(pixel);read(pixel);}
 function imageReady(){if(!bitmap.current)return;const next=document.createElement('canvas');next.width=256;next.height=256;next.getContext('2d')?.drawImage(bitmap.current,0,0,256,256);canvas.current=next;if(selected)read(selected);}
 useEffect(()=>{const element=stage.current;if(!element)return;const measure=()=>{const width=element.getBoundingClientRect().width,old=sizeRef.current;sizeRef.current=width;setSize(width);const current=viewRef.current;apply({...current,x:old?current.x*width/old:0,y:old?current.y*width/old:0});pointers.current.clear();gesture.current=null;};measure();const observer=new ResizeObserver(measure);observer.observe(element);return()=>observer.disconnect();},[]);
 useEffect(()=>{const element=stage.current;if(!element)return;const wheel=(event:WheelEvent)=>{event.preventDefault();apply(zoomAt(viewRef.current,viewRef.current.scale*Math.exp(-event.deltaY*.002),centered(event.clientX,event.clientY),sizeRef.current));};element.addEventListener('wheel',wheel,{passive:false});return()=>element.removeEventListener('wheel',wheel);},[]);
 function down(event:React.PointerEvent<HTMLDivElement>){if(event.button!==0||pointers.current.size>=2)return;event.preventDefault();event.currentTarget.focus({preventScroll:true});event.currentTarget.setPointerCapture(event.pointerId);const point=centered(event.clientX,event.clientY);pointers.current.set(event.pointerId,point);if(pointers.current.size===1)tap.current={pointerId:event.pointerId,point,time:Date.now(),moved:false};else if(tap.current)tap.current.moved=true;seed();}
 function move(event:React.PointerEvent<HTMLDivElement>){if(!pointers.current.has(event.pointerId))return;event.preventDefault();const point=centered(event.clientX,event.clientY);pointers.current.set(event.pointerId,point);if(tap.current&&distance(tap.current.point,point)>6){tap.current.moved=true;lastTap.current=null;}const start=gesture.current,points=[...pointers.current.values()];if(!start)return;
  if(points.length===2&&start.points.length===2){const before=middle(start.points[0],start.points[1]),after=middle(points[0],points[1]),scale=Math.max(1,Math.min(MAX_SCALE,start.view.scale*distance(points[0],points[1])/Math.max(1,distance(start.points[0],start.points[1])))),ratio=scale/start.view.scale;apply({scale,x:after.x-(before.x-start.view.x)*ratio,y:after.y-(before.y-start.view.y)*ratio});}
  else if(points.length===1&&start.points.length===1)apply({...start.view,x:start.view.x+point.x-start.points[0].x,y:start.view.y+point.y-start.points[0].y});
 }
 function up(event:React.PointerEvent<HTMLDivElement>,cancelled=false){if(!pointers.current.has(event.pointerId))return;const point=centered(event.clientX,event.clientY),candidate=tap.current;
  if(!cancelled&&candidate?.pointerId===event.pointerId&&!candidate.moved&&distance(candidate.point,point)<6&&Date.now()-candidate.time<600&&pointers.current.size===1){choose(pixelAt(viewRef.current,point,sizeRef.current));const previous=lastTap.current;if(previous&&Date.now()-previous.time<350&&distance(previous.point,point)<24){apply(zoomAt(viewRef.current,viewRef.current.scale>=MAX_SCALE?1:viewRef.current.scale*2,point,sizeRef.current));lastTap.current=null;}else lastTap.current={point,time:Date.now()};}
  pointers.current.delete(event.pointerId);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);tap.current=null;seed();
 }
 function keyboard(event:React.KeyboardEvent<HTMLDivElement>){const current=viewRef.current,step=32;let next:View|undefined;if(event.key==='+'||event.key==='=')next=zoomAt(current,current.scale*2,{x:0,y:0},sizeRef.current);else if(event.key==='-')next=zoomAt(current,current.scale/2,{x:0,y:0},sizeRef.current);else if(event.key==='ArrowLeft')next={...current,x:current.x+step};else if(event.key==='ArrowRight')next={...current,x:current.x-step};else if(event.key==='ArrowUp')next={...current,y:current.y+step};else if(event.key==='ArrowDown')next={...current,y:current.y-step};else if(event.key==='Home')next=fullView();else if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(pixelAt(current,{x:0,y:0},sizeRef.current));}if(next){event.preventDefault();apply(next);}}
 const selectedPosition=selected?pixelPosition(view,selected,size):null,minePosition=mine?pixelPosition(view,mine,size):null,pixelSize=size*view.scale/256,posted=selected&&positions?.includes(selected.y*256+selected.x),self=selected&&mine&&selected.x===mine.x&&selected.y===mine.y;
 function mark(point:Point,kind:string){return <span className={'explorer-marker '+kind} style={{left:point.x,top:point.y,width:Math.max(5,pixelSize),height:Math.max(5,pixelSize)}}/>;}
 return <div className="global-explorer">
  <p className="explorer-help" id="explorer-help">{t('demo.global.gestures')}</p>
  <div className="global-overview artboard explorer-stage" ref={stage} role="region" tabIndex={0} aria-label={t('demo.global.explore')} aria-describedby="explorer-help" data-testid="global-explorer" data-scale={view.scale} data-pan-x={view.x} data-pan-y={view.y} onPointerDown={down} onPointerMove={move} onPointerUp={event=>up(event)} onPointerCancel={event=>up(event,true)} onLostPointerCapture={event=>{if(pointers.current.has(event.pointerId))up(event,true);}} onKeyDown={keyboard}>
   <img ref={bitmap} src={image} onLoad={imageReady} alt={t('global.label')} draggable={false} style={{transform:`matrix(${view.scale},0,0,${view.scale},${view.x},${view.y})`}}/>
   {minePosition&&mark(minePosition,'mine')}{selectedPosition&&mark(selectedPosition,'selected')}
  </div>
  <div className="explorer-controls"><button type="button" disabled={view.scale<=1} aria-label={t('demo.global.smaller')} onClick={()=>apply(zoomAt(viewRef.current,viewRef.current.scale/2,{x:0,y:0},sizeRef.current))}>−</button><label><span className="mono">{t('demo.global.scale',{n:Number(view.scale.toFixed(1))})}</span><input aria-label={t('demo.global.scale_control')} type="range" min="1" max={MAX_SCALE} step=".25" value={view.scale} onChange={event=>apply(zoomAt(viewRef.current,Number(event.target.value),{x:0,y:0},sizeRef.current))}/></label><button type="button" disabled={view.scale>=MAX_SCALE} aria-label={t('demo.global.larger')} onClick={()=>apply(zoomAt(viewRef.current,viewRef.current.scale*2,{x:0,y:0},sizeRef.current))}>＋</button><button type="button" className="text-button" onClick={()=>{apply(fullView());setSelected(null);setColor('');lastTap.current=null;}}>{t('demo.global.reset')}</button></div>
  {selected&&<div className="pixel-inspection" data-testid="global-pixel-inspection" data-x={selected.x} data-y={selected.y}><div className="pixel-swatch" style={{background:color||'transparent'}} aria-hidden="true"/><div><p>{t(sample?'demo.global.sample_pixel':self?'schiild.regions.mine':posted?'demo.global.selected_schiil':'demo.global.empty_pixel')}</p><p className="mono">{t('global.coords',selected)}</p>{color&&<p className="mono">{t('demo.global.color',{color})}</p>}</div></div>}
  <p className="shared-note">{t('demo.global.pixel_note')}</p>
 </div>;
}
