import 'reflect-metadata';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {resolve} from 'node:path';
import pg from 'pg';
import sharp from 'sharp';
import {WebSocket} from 'ws';
import {once} from 'node:events';
import {Database} from '../dist/database.js';
import {createApi} from '../dist/http.js';
import {RustEngine} from '../dist/adapters.js';
import {DailyGeneration} from '../dist/daily.js';
import {lotteryOrder} from '../dist/lottery.js';
const repo=resolve(import.meta.dirname,'../../..');
test('authenticated HTTP, JPEG atomic submission, UTC boundary, real generation, lottery and fanout',{timeout:60000},async()=>{
 const adminUrl=process.env.DATABASE_URL;if(!adminUrl)throw Error('DATABASE_URL required');
 const admin=new pg.Client({connectionString:adminUrl});await admin.connect();
 const databaseName='schiild_api_test_'+randomUUID().replaceAll('-','');
 await admin.query(`CREATE DATABASE ${databaseName}`);
 const url=new URL(adminUrl);url.pathname='/'+databaseName;
 let db,server,socket;
 try{
  execFileSync(process.execPath,[resolve(repo,'apps/api/scripts/migrate.mjs')],{env:{...process.env,DATABASE_URL:url.toString()},stdio:'pipe'});
  db=new Database(url.toString());
  const first=randomUUID(),second=randomUUID(),atelier=randomUUID();
  await db.pool.query("INSERT INTO users(id,handle,display_name,verification_tier,firebase_uid) VALUES($1,'api_one','One',1,'one'),($2,'api_two','Two',1,'two')",[first,second]);
  await db.pool.query("INSERT INTO ateliers(id,name,capacity,invite_code,created_by) VALUES($1,'Test',2,'test',$2)",[atelier,first]);
  await db.pool.query("INSERT INTO atelier_members(atelier_id,user_id,role,slot_index) VALUES($1,$2,'creator',0),($1,$3,'member',1)",[atelier,first,second]);
  const objects=new Map();let failStore=false;
  const store={put:async(key,bytes)=>{if(failStore)throw Error('storage_unavailable');objects.set(key,bytes);},get:async key=>{if(!objects.has(key))throw Error('missing');return objects.get(key);},remove:async key=>{objects.delete(key);}};
  const engine=new RustEngine(store,resolve(repo,process.platform==='win32'?'target/release/gen.exe':'target/release/gen'),resolve(repo,'target/wasm32-unknown-unknown/release/gen.wasm'),resolve(repo,'services/gen/palettes/provisional-32.json'));
  let moderation={decision:'approved'},moderationOutage=false;
  let now=new Date('2030-01-01T23:59:00Z');
  const auth={verify:async token=>{if(!['one','two'].includes(token))throw Error('invalid');return {uid:token};}};
  server=await createApi({db,store,engine,auth,moderator:{review:async()=>{if(moderationOutage)throw Error('moderation_unavailable');return moderation;}},now:()=>now});
  await server.app.listen(0,'127.0.0.1');const base=await server.app.getUrl();
  async function request(path,{token='one',body,method='GET'}={}){const headers={};if(token)headers.authorization=`Bearer ${token}`;if(body && !(body instanceof FormData))headers['content-type']='application/json';return fetch(base+'/v1/'+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});}
  const image=await sharp({create:{width:1080,height:1080,channels:3,background:'#456789'}}).withMetadata({exif:{IFD0:{Copyright:'test-exif'}}}).jpeg().toBuffer();
  async function upload(token='one',bytes=image,ateliers=[atelier]){const form=new FormData();form.set('image',new Blob([bytes],{type:'image/jpeg'}),'photo.jpg');form.set('atelier_ids',JSON.stringify(ateliers));return request('schiils',{token,body:form,method:'POST'});}
  assert.equal((await request('ateliers',{token:null})).status,401);
  assert.equal((await request('ateliers',{token:'forged'})).status,401);
  const wrong=await sharp({create:{width:100,height:100,channels:3,background:'#000000'}}).jpeg().toBuffer();assert.equal((await upload('one',wrong)).status,400);
  moderationOutage=true;assert.equal((await upload()).status,503);moderationOutage=false;
  failStore=true;assert.equal((await upload()).status,503);failStore=false;
  assert.equal(Number((await db.pool.query('SELECT count(*) FROM schiils')).rows[0].count),0);
  socket=new WebSocket(base.replace('http:','ws:')+`/v1/ateliers/${atelier}/live`);await once(socket,'open');
  const initial=once(socket,'message');socket.send(JSON.stringify({token:'one'}));assert.equal(JSON.parse((await initial)[0].toString()).recordedCount,0);
  const changed=once(socket,'message');
  const responses=await Promise.all([upload(),upload()]);
  assert.equal(JSON.parse((await changed)[0].toString()).recordedCount,1);assert.deepEqual(responses.map(r=>r.status).sort(),[201,409]);
  const created=await responses.find(r=>r.status===201).json(),conflict=await responses.find(r=>r.status===409).json();assert.equal(conflict.action.href,`/v1/schiils/${created.schiilId}/posts`);
  assert.equal((await sharp(objects.get(`schiils/${created.schiilId}.jpg`)).metadata()).exif,undefined);
  const otherAtelier=await (await request('ateliers',{method:'POST',body:{name:'Other',capacity:2}})).json();
  assert.equal((await request(`schiils/${created.schiilId}/posts`,{method:'POST',body:{atelier_ids:[otherAtelier.atelier_id]}})).status,201);
  assert.equal((await request(`schiils/${created.schiilId}/posts`,{method:'POST',token:'two',body:{atelier_ids:[atelier]}})).status,404);
  const today=await (await request(`ateliers/${atelier}/today`)).json();assert.equal(today.provisional,true);assert.equal(today.tiles.length,2);assert.equal(JSON.stringify(today).includes(first),false);assert.equal(JSON.stringify(today).includes(second),false);
  const directLayout=await engine.layout(atelier,'2030-01-01',[(await db.pool.query('SELECT image_sha256 FROM schiils WHERE id=$1',[created.schiilId])).rows[0].image_sha256],2);assert.deepEqual(today.tiles.map(t=>t.rect),directLayout);
  assert.equal((await upload('two')).status,201);
  now=new Date('2030-01-02T00:01:00Z');assert.equal((await upload()).status,201);
  assert.deepEqual((await db.pool.query('SELECT schiild_date::text FROM schiils WHERE user_id=$1 ORDER BY schiild_date',[first])).rows.map(r=>r.schiild_date),['2030-01-01','2030-01-02']);
  assert.equal((await request(`schiils/${created.schiilId}/posts`,{method:'POST',body:{atelier_ids:[atelier]}})).status,409);
  const daily=new DailyGeneration(db,engine,store);const generated=await daily.run('2030-01-01',atelier);assert.equal(generated.status,'succeeded');assert.equal((await daily.run('2030-01-01',atelier)).status,'existing');
  const work=(await db.pool.query('SELECT * FROM schiilds WHERE id=$1',[generated.schiildId])).rows[0];assert.notEqual(work.lottery_seed,work.generation_seed);assert.deepEqual(work.lottery_order,lotteryOrder(work.lottery_seed,[first,second]));
  const publicLottery=await request(`schiilds/${generated.schiildId}/lottery`,{token:null});assert.equal(publicLottery.status,200);
  for(const userId of work.lottery_order){const result=await request(`schiilds/${generated.schiildId}/decline`,{method:'POST',token:userId===first?'one':'two'});assert.equal(result.status,201);}
  assert.equal((await db.pool.query('SELECT custodian_user_id FROM schiild_custody WHERE schiild_id=$1',[generated.schiildId])).rows[0].custodian_user_id,null);
  const global=await daily.run('2030-01-01',null);assert.equal(global.status,'succeeded');
  assert.equal((await db.pool.query('SELECT custodian_user_id FROM schiild_custody WHERE schiild_id=$1',[global.schiildId])).rows[0].custodian_user_id,null);
  moderation={decision:'rejected',reason:'person'};now=new Date('2030-01-03T12:00:00Z');
  const rejectedResponse=await upload();assert.equal(rejectedResponse.status,201);const rejected=await rejectedResponse.json();assert.equal(rejected.moderation.reason,'person');
  assert.equal((await upload()).status,409);
  assert.equal((await db.pool.query('SELECT reason FROM moderation_outbox WHERE schiil_id=$1',[rejected.schiilId])).rows[0].reason,'person');
  await db.pool.query('INSERT INTO push_devices(user_id,token) VALUES($1,$2)',[first,'fixture-device']);const notices=[];await daily.deliverModeration({send:async(token,data)=>notices.push({token,data})});await daily.deliverModeration({send:async()=>assert.fail('duplicate notice')});assert.equal(notices.length,1);assert.equal(notices[0].data.reason,'person');
  const excluded=await daily.run('2030-01-03',atelier);assert.equal(excluded.status,'succeeded');assert.equal(Number((await db.pool.query('SELECT participant_count FROM schiilds WHERE id=$1',[excluded.schiildId])).rows[0].participant_count),0);
  const broken=new DailyGeneration(db,{...engine,generate:async()=>{throw Error('forced');}},store);await assert.rejects(broken.run('2029-12-31',atelier));
  assert.equal((await db.pool.query("SELECT status FROM generation_jobs WHERE schiild_date='2029-12-31' AND atelier_id=$1",[atelier])).rows[0].status,'failed');assert.equal(Number((await db.pool.query("SELECT count(*) FROM schiilds WHERE schiild_date='2029-12-31'")).rows[0].count),0);
  await assert.rejects(daily.notifications('2030-01-01',new Date('2030-01-02T00:14:59Z')));
  await daily.notifications('2030-01-01',new Date('2030-01-02T00:15:00Z'));await daily.notifications('2030-01-01',new Date('2030-01-02T00:15:00Z'));
  assert.equal(Number((await db.pool.query('SELECT count(*) FROM notification_outbox')).rows[0].count),2);
  const payloads=(await db.pool.query('SELECT payload FROM notification_outbox')).rows.map(r=>r.payload);assert(payloads.every(p=>!JSON.stringify(p).includes(first)));
 }finally{if(socket)socket.terminate();if(server)await server.close();if(db)await db.pool.end();await admin.query(`DROP DATABASE ${databaseName}`);await admin.end();}
});
